pre-commit evolution

diff --git a/phpcs-pre-commit/pre-commit b/phpcs-pre-commit/pre-commit
--- a/phpcs-pre-commit/pre-commit
+++ b/phpcs-pre-commit/pre-commit
@@ -124,6 +124,8 @@ if [ $RETVAL_PHPMD -ne 0 ]; then
     echo "PHP Mess Detector errors have been detected... Report has been written in $PRECOMMIT_LOG file"
 fi
 if [ $BLOCK_ON_ERRORS -ne 0 ]; then
-  exit $RETVAL_PHPCS+$RETVAL_PHPMD
+    $RETURN_CODE=$RETVAL_PHPCS+$RETVAL_PHPMD
+    echo "The hook has been configured to block on error. returning status code $RETURN_CODE"
+    exit $RETURN_CODE
 fi
 exit 0
